// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

console.log('--- PRISMA CONFIG DEBUG ---');
console.log('DATABASE_URL present:', !!process.env["DATABASE_URL"]);
console.log('DIRECT_URL present:', !!process.env["DIRECT_URL"]);

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "ts-node prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
