import { createClient } from '@supabase/supabase-js'
import { randomUUID } from 'crypto'
import * as dotenv from 'dotenv'

dotenv.config({ path: '.env' })
dotenv.config({ path: '.env.local' })

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

// Enum values mapped to DB strings
const FacilityType = {
  templeGrave: '寺院墓地',
  privateGraveyard: '民営霊園',
  publicGraveyard: '公営霊園',
  ossuary: '納骨堂',
  complex: '複合型',
  other: 'その他',
} as const

const ReligionCategory = {
  buddhism: 'buddhism',
  shinto: 'shinto',
  christianity: 'christianity',
  other: 'other',
  unknown: 'unknown',
} as const

const BuddhistSect = {
  tendai: 'tendai', shingon: 'shingon', jodo: 'jodo', jodoShin: 'jodoShin',
  rinzai: 'rinzai', soto: 'soto', other: 'other', unknown: 'unknown',
} as const

const temples = [
  // ── 東京都 ──────────────────────────────────────────────────
  {
    name: '清蓮寺 新宿永代供養墓',
    kana: 'せいれんじ しんじゅくえいたいくようぼ',
    type: FacilityType.templeGrave,
    religion: ReligionCategory.buddhism,
    buddhistSect: BuddhistSect.jodo,
    prefecture: '東京都',
    prefectureCode: 13,
    cityName: '新宿区',
    addressLine: '西新宿2-1-1',
    address: '東京都新宿区西新宿2-1-1',
    lat: 35.6896,
    lng: 139.6917,
    access: 'JR新宿駅 西口より徒歩8分',
    parkingAvailable: true,
    parking: '近隣コインパーキング利用（寺院提携あり）',
    indoorOutdoor: 'outdoor',
    barrierFree: true,
    barrierFreeLabel: '車椅子でのアクセス可能',
    petAllowed: 'no',
    sects: ['jodo', 'other'],
    supportedMemorialTypes: ['eitai_kuyou', 'jumokusou', 'general'],
    nearestStations: [
      { name: '新宿駅', line: 'JR中央線', walk: 8 },
      { name: '都庁前駅', line: '東京都営地下鉄大江戸線', walk: 3 },
    ],
    priceAggMin: 280000,
    priceAggMax: 980000,
    managementFeeAggType: 'monthly',
    catchphrase: '都心にありながら、緑に囲まれた静かな境内',
    overview: '新宿区西新宿に位置する浄土宗の寺院。都心のビル群の中にありながら、四季折々の草花と緑に包まれた境内が特徴です。宗旨・宗派を問わず、どなたでも受け入れております。',
    suitableFor: ['継承者なし', '都心へのアクセス重視', '宗派不問'],
    notesPoints: ['年間管理費が必要です', '合同法要は毎月第2日曜日に実施'],
    tags: ['新宿', '都心', '永代供養', '樹木葬', 'バリアフリー'],
    phone: '03-0000-0001',
    officeHours: '9:00〜17:00（年中無休）',
    status: 'public',
    listedInSearch: true,
    zipCode: '160-0023',
    planType: 'free',
    plans: [
      {
        category: 'eitai_kuyou',
        name: '永代供養墓（個別型）',
        subDescription: '個別スペースで33年間安置後、合祀',
        price: 580000,
        priceNote: '永代使用料込み',
        managementFee: 5000,
        availability: 'available',
        burialMethod: 'burial',
        periodType: 'fixed',
        periodYears: 33,
        capacity: '2名',
        petAllowed: 'no',
        order: 0,
      },
      {
        category: 'eitai_kuyou',
        name: '永代供養墓（合祀型）',
        subDescription: '納骨後すぐに合祀。管理費不要',
        price: 98000,
        priceNote: '一体あたり',
        managementFee: 0,
        availability: 'available',
        burialMethod: 'ossuary',
        periodType: 'perpetual',
        petAllowed: 'no',
        order: 1,
      },
      {
        category: 'jumokusou',
        name: '樹木葬（里山タイプ）',
        subDescription: 'シンボルツリー「ソメイヨシノ」の根元に眠る',
        price: 280000,
        priceNote: '永代使用料・埋葬料込み',
        managementFee: 3000,
        availability: 'available',
        burialMethod: 'tree',
        periodType: 'perpetual',
        capacity: '1名',
        petAllowed: 'no',
        order: 2,
      },
    ],
  },
  {
    name: '青山霊園 渋谷納骨堂',
    kana: 'あおやまれいえん しぶやのうこつどう',
    type: FacilityType.ossuary,
    religion: ReligionCategory.buddhism,
    buddhistSect: BuddhistSect.soto,
    prefecture: '東京都',
    prefectureCode: 13,
    cityName: '渋谷区',
    addressLine: '神宮前5-10-2',
    address: '東京都渋谷区神宮前5-10-2',
    lat: 35.6651,
    lng: 139.7090,
    access: '地下鉄表参道駅 B2出口より徒歩5分',
    parkingAvailable: false,
    indoorOutdoor: 'indoor',
    barrierFree: true,
    barrierFreeLabel: 'エレベーター完備・全フロアバリアフリー',
    petAllowed: 'allowed',
    sects: ['soto', 'rinzai', 'other'],
    supportedMemorialTypes: ['noukotsudou', 'eitai_kuyou'],
    nearestStations: [
      { name: '表参道駅', line: '東京メトロ半蔵門線', walk: 5 },
      { name: '明治神宮前駅', line: '東京メトロ千代田線', walk: 7 },
    ],
    priceAggMin: 150000,
    priceAggMax: 650000,
    managementFeeAggType: 'annual',
    catchphrase: '表参道からすぐ。手ぶらで訪れても気軽にお参りできる屋内型納骨堂',
    overview: '渋谷区神宮前に位置する現代的な屋内型納骨堂。雨の日も天候を気にせずお参りいただけます。ICカードで扉が開く最新設備を備えており、参拝ブースにはパネルに故人の写真や思い出を映し出すシステムを採用。',
    suitableFor: ['天候に関係なくお参りしたい', 'ペットと一緒に眠りたい', '交通の便を重視'],
    notesPoints: ['年間管理費が必要です', 'ICカードによる入退館管理'],
    tags: ['渋谷', '表参道', '納骨堂', '屋内', 'バリアフリー', 'ペット可'],
    phone: '03-0000-0002',
    officeHours: '8:00〜20:00（年中無休）',
    status: 'public',
    listedInSearch: true,
    zipCode: '150-0001',
    planType: 'free',
    plans: [
      {
        category: 'noukotsudou',
        name: 'プレミアム個室ブース',
        subDescription: '専用参拝ブース付き・デジタル遺影パネル完備',
        price: 650000,
        priceNote: '永代使用料',
        managementFee: 18000,
        availability: 'available',
        burialMethod: 'indoor',
        periodType: 'perpetual',
        capacity: '4名',
        petAllowed: 'allowed',
        order: 0,
      },
      {
        category: 'noukotsudou',
        name: 'スタンダード個別壇',
        subDescription: '共用参拝スペースでのお参り',
        price: 250000,
        priceNote: '永代使用料',
        managementFee: 12000,
        availability: 'available',
        burialMethod: 'indoor',
        periodType: 'perpetual',
        capacity: '2名',
        petAllowed: 'allowed',
        order: 1,
      },
      {
        category: 'eitai_kuyou',
        name: '永代供養プラン',
        subDescription: '管理費不要・合祀型',
        price: 150000,
        managementFee: 0,
        availability: 'available',
        burialMethod: 'ossuary',
        periodType: 'perpetual',
        petAllowed: 'no',
        order: 2,
      },
    ],
  },
  {
    name: '世田谷浄苑 樹木葬墓地',
    kana: 'せたがやじょうえん じゅもくそうぼち',
    type: FacilityType.privateGraveyard,
    religion: ReligionCategory.unknown,
    prefecture: '東京都',
    prefectureCode: 13,
    cityName: '世田谷区',
    addressLine: '砧3-5-12',
    address: '東京都世田谷区砧3-5-12',
    lat: 35.6332,
    lng: 139.6265,
    access: '小田急線 成城学園前駅より徒歩12分／バス停「砧公園」より徒歩3分',
    parkingAvailable: true,
    parking: '無料駐車場20台',
    indoorOutdoor: 'outdoor',
    barrierFree: true,
    barrierFreeLabel: '園内はスロープ整備済み',
    petAllowed: 'allowed',
    sects: [],
    supportedMemorialTypes: ['jumokusou', 'eitai_kuyou'],
    nearestStations: [
      { name: '成城学園前駅', line: '小田急小田原線', walk: 12 },
    ],
    priceAggMin: 198000,
    priceAggMax: 480000,
    managementFeeAggType: 'none',
    catchphrase: '宗旨・宗派不問。ペットと一緒に眠れる自然葬',
    overview: '世田谷区砧の閑静な住宅街に位置する自然葬霊園。宗旨・宗派を問わず、ペットとの合葬もできる樹木葬が人気です。管理費不要のプランが中心で、シンプルな永代供養を求める方に支持されています。',
    suitableFor: ['ペットと一緒に眠りたい', '宗派不問', '管理費をかけたくない'],
    notesPoints: ['ペット同伴でのお参り可能（リードで管理のこと）', '見学は随時受付中'],
    tags: ['世田谷', '樹木葬', 'ペット可', '宗派不問', '管理費不要'],
    phone: '03-0000-0003',
    officeHours: '9:00〜16:30（月曜定休）',
    status: 'public',
    listedInSearch: true,
    zipCode: '157-0073',
    planType: 'free',
    plans: [
      {
        category: 'jumokusou',
        name: '桜の樹木葬（個別）',
        subDescription: 'ソメイヨシノのシンボルツリー周辺に個別埋葬',
        price: 480000,
        managementFee: 0,
        availability: 'available',
        burialMethod: 'tree',
        periodType: 'perpetual',
        capacity: '2名',
        petAllowed: 'allowed',
        order: 0,
      },
      {
        category: 'jumokusou',
        name: '花壇葬（ガーデニング型）',
        subDescription: '季節の草花に囲まれた花壇区画',
        price: 198000,
        managementFee: 0,
        availability: 'available',
        burialMethod: 'tree',
        periodType: 'perpetual',
        capacity: '1名',
        petAllowed: 'allowed',
        order: 1,
      },
    ],
  },
  {
    name: '港区立 青山霊園',
    kana: 'みなとくりつ あおやまれいえん',
    type: FacilityType.publicGraveyard,
    religion: ReligionCategory.unknown,
    prefecture: '東京都',
    prefectureCode: 13,
    cityName: '港区',
    addressLine: '南青山2-32-2',
    address: '東京都港区南青山2-32-2',
    lat: 35.6682,
    lng: 139.7176,
    access: '地下鉄外苑前駅 1番出口より徒歩5分',
    parkingAvailable: true,
    parking: '園内駐車場あり（無料）',
    indoorOutdoor: 'outdoor',
    barrierFree: false,
    petAllowed: 'no',
    sects: [],
    supportedMemorialTypes: ['general'],
    nearestStations: [
      { name: '外苑前駅', line: '東京メトロ銀座線', walk: 5 },
    ],
    priceAggMin: 50000,
    priceAggMax: 300000,
    managementFeeAggType: 'annual',
    catchphrase: '都内最大級の公営霊園。緑豊かな環境で安心の行政運営',
    overview: '東京都港区が運営する公営霊園。都内最大規模の霊園のひとつで、著名人の墓所としても知られています。公営のため安心感が高く、費用も民営と比べて抑えられるのが特徴です。',
    suitableFor: ['費用を抑えたい', '行政の安心感を求める'],
    notesPoints: ['申込には東京都の住民登録が必要', '抽選により使用権を取得'],
    tags: ['港区', '青山', '公営', '霊園'],
    phone: '03-0000-0004',
    officeHours: '8:30〜17:00（土日祝も開園）',
    status: 'public',
    listedInSearch: true,
    zipCode: '107-0062',
    planType: 'free',
    plans: [
      {
        category: 'general',
        name: '一般墓地（芝生区画）',
        subDescription: '4㎡区画。使用者名義で管理',
        price: 300000,
        priceNote: '永代使用料（別途墓石代が必要）',
        managementFee: 12000,
        availability: 'available',
        burialMethod: 'burial',
        periodType: 'perpetual',
        petAllowed: 'no',
        order: 0,
      },
      {
        category: 'general',
        name: '一般墓地（通常区画）',
        price: 50000,
        priceNote: '永代使用料（別途墓石代が必要）',
        managementFee: 8000,
        availability: 'available',
        burialMethod: 'burial',
        periodType: 'perpetual',
        petAllowed: 'no',
        order: 1,
      },
    ],
  },

  // ── 大阪府 ──────────────────────────────────────────────────
  {
    name: '四天王寺 永代供養墓',
    kana: 'してんのうじ えいたいくようぼ',
    type: FacilityType.templeGrave,
    religion: ReligionCategory.buddhism,
    buddhistSect: BuddhistSect.tendai,
    prefecture: '大阪府',
    prefectureCode: 27,
    cityName: '大阪市天王寺区',
    addressLine: '四天王寺1-11-18',
    address: '大阪府大阪市天王寺区四天王寺1-11-18',
    lat: 34.6554,
    lng: 135.5148,
    access: '地下鉄四天王寺前夕陽ヶ丘駅より徒歩5分',
    parkingAvailable: true,
    parking: '境内駐車場（有料）',
    indoorOutdoor: 'outdoor',
    barrierFree: true,
    barrierFreeLabel: '参道は段差なし・車椅子対応',
    petAllowed: 'no',
    sects: ['tendai', 'other'],
    supportedMemorialTypes: ['eitai_kuyou', 'general', 'noukotsudou'],
    nearestStations: [
      { name: '四天王寺前夕陽ヶ丘駅', line: '大阪メトロ谷町線', walk: 5 },
    ],
    priceAggMin: 100000,
    priceAggMax: 800000,
    managementFeeAggType: 'annual',
    catchphrase: '1400年の歴史を持つ大阪最古の寺院で、安心の永代供養',
    overview: '聖徳太子が建立した日本最古の官寺のひとつ。長い歴史と伝統のある境内で、宗派を超えて多くの方に安心の永代供養を提供しています。',
    suitableFor: ['歴史ある寺院を希望', '大阪市内でアクセスしやすい場所'],
    notesPoints: ['年間法要は春・秋の2回実施', '事前見学を推奨'],
    tags: ['大阪', '天王寺', '永代供養', '歴史', '仏教'],
    phone: '06-0000-0001',
    officeHours: '9:00〜16:30（年中無休）',
    status: 'public',
    listedInSearch: true,
    zipCode: '543-0051',
    planType: 'free',
    plans: [
      {
        category: 'eitai_kuyou',
        name: '個別永代供養墓',
        subDescription: '50年間個別安置後、大型合祀墓へ',
        price: 800000,
        managementFee: 10000,
        availability: 'available',
        burialMethod: 'burial',
        periodType: 'fixed',
        periodYears: 50,
        capacity: '夫婦2名',
        petAllowed: 'no',
        order: 0,
      },
      {
        category: 'eitai_kuyou',
        name: '合祀永代供養',
        subDescription: '即日合祀。管理費・法要費込み',
        price: 100000,
        managementFee: 0,
        availability: 'available',
        burialMethod: 'ossuary',
        periodType: 'perpetual',
        petAllowed: 'no',
        order: 1,
      },
    ],
  },
  {
    name: '豊中メモリアルガーデン',
    kana: 'とよなかめもりあるがーでん',
    type: FacilityType.privateGraveyard,
    religion: ReligionCategory.unknown,
    prefecture: '大阪府',
    prefectureCode: 27,
    cityName: '豊中市',
    addressLine: '宮山町4-12-1',
    address: '大阪府豊中市宮山町4-12-1',
    lat: 34.7825,
    lng: 135.4680,
    access: '阪急宝塚線 豊中駅より車で8分／無料送迎バスあり',
    parkingAvailable: true,
    parking: '無料駐車場100台',
    indoorOutdoor: 'outdoor',
    barrierFree: true,
    barrierFreeLabel: '全エリアバリアフリー対応',
    petAllowed: 'allowed',
    sects: [],
    supportedMemorialTypes: ['general', 'jumokusou', 'eitai_kuyou'],
    nearestStations: [
      { name: '豊中駅', line: '阪急宝塚線', walk: 999 },
    ],
    priceAggMin: 148000,
    priceAggMax: 1200000,
    managementFeeAggType: 'annual',
    catchphrase: '広大な敷地に多彩なプランを揃えた大阪北部の総合霊園',
    overview: '豊中市に位置する民営総合霊園。一般墓地から樹木葬、永代供養まで幅広いプランを揃え、宗旨・宗派不問。無料送迎バスを毎日運行しているので、車がない方も安心してお参りできます。',
    suitableFor: ['車でのアクセスを重視', '多彩なプランから選びたい', '宗派不問'],
    notesPoints: ['送迎バスは予約不要', '資料請求で5,000円割引券進呈'],
    tags: ['豊中', '大阪', '民営霊園', '樹木葬', 'ペット可', 'バリアフリー'],
    phone: '06-0000-0002',
    officeHours: '9:00〜17:00（年中無休）',
    status: 'public',
    listedInSearch: true,
    zipCode: '560-0015',
    planType: 'free',
    plans: [
      {
        category: 'general',
        name: '一般墓地 洋型墓石',
        price: 1200000,
        priceNote: '墓石・工事費込み',
        managementFee: 15000,
        availability: 'available',
        burialMethod: 'burial',
        periodType: 'perpetual',
        capacity: '家族全員',
        petAllowed: 'allowed',
        order: 0,
      },
      {
        category: 'jumokusou',
        name: '樹木葬 ガーデンプラン',
        price: 248000,
        managementFee: 0,
        availability: 'available',
        burialMethod: 'tree',
        periodType: 'perpetual',
        capacity: '2名',
        petAllowed: 'allowed',
        order: 1,
      },
      {
        category: 'eitai_kuyou',
        name: '永代供養 合祀プラン',
        price: 148000,
        managementFee: 0,
        availability: 'available',
        burialMethod: 'ossuary',
        periodType: 'perpetual',
        petAllowed: 'no',
        order: 2,
      },
    ],
  },

  // ── 神奈川県 ─────────────────────────────────────────────────
  {
    name: '鎌倉 円覚寺 永代供養',
    kana: 'かまくら えんがくじ えいたいくよう',
    type: FacilityType.templeGrave,
    religion: ReligionCategory.buddhism,
    buddhistSect: BuddhistSect.rinzai,
    prefecture: '神奈川県',
    prefectureCode: 14,
    cityName: '鎌倉市',
    addressLine: '山ノ内409',
    address: '神奈川県鎌倉市山ノ内409',
    lat: 35.3387,
    lng: 139.5501,
    access: 'JR横須賀線 北鎌倉駅より徒歩2分',
    parkingAvailable: false,
    indoorOutdoor: 'outdoor',
    barrierFree: false,
    petAllowed: 'no',
    sects: ['rinzai'],
    supportedMemorialTypes: ['eitai_kuyou', 'general'],
    nearestStations: [
      { name: '北鎌倉駅', line: 'JR横須賀線', walk: 2 },
    ],
    priceAggMin: 300000,
    priceAggMax: 1500000,
    managementFeeAggType: 'annual',
    catchphrase: '鎌倉を代表する名刹の境内に眠る、格式ある永代供養',
    overview: '鎌倉五山第二位に列せられる名刹・円覚寺の境内に設けられた永代供養墓。禅の空気の中、四季折々の豊かな自然に包まれた安らぎの場所です。宗派を問わず受け入れています。',
    suitableFor: ['格式ある寺院を希望', '鎌倉・湘南エリアにゆかりがある'],
    notesPoints: ['境内は世界遺産候補のため、墓石の形式に制限あり', '見学は境内拝観時間内'],
    tags: ['鎌倉', '円覚寺', '禅宗', '永代供養', '世界遺産'],
    phone: '0467-00-0001',
    officeHours: '8:00〜17:00',
    status: 'public',
    listedInSearch: true,
    zipCode: '247-0062',
    planType: 'free',
    plans: [
      {
        category: 'eitai_kuyou',
        name: '境内永代供養墓（個別）',
        price: 1500000,
        managementFee: 20000,
        availability: 'available',
        burialMethod: 'burial',
        periodType: 'fixed',
        periodYears: 33,
        capacity: '夫婦2名',
        petAllowed: 'no',
        order: 0,
      },
      {
        category: 'eitai_kuyou',
        name: '合祀供養墓',
        price: 300000,
        managementFee: 0,
        availability: 'available',
        burialMethod: 'ossuary',
        periodType: 'perpetual',
        petAllowed: 'no',
        order: 1,
      },
    ],
  },
  {
    name: '横浜メモリアルパーク 緑区',
    kana: 'よこはまめもりあるぱーく みどりく',
    type: FacilityType.complex,
    religion: ReligionCategory.unknown,
    prefecture: '神奈川県',
    prefectureCode: 14,
    cityName: '横浜市緑区',
    addressLine: '三保町1-15',
    address: '神奈川県横浜市緑区三保町1-15',
    lat: 35.5090,
    lng: 139.5710,
    access: 'JR横浜線 鴨居駅より無料シャトルバス10分',
    parkingAvailable: true,
    parking: '無料駐車場300台',
    indoorOutdoor: 'outdoor',
    barrierFree: true,
    barrierFreeLabel: '全エリア車椅子対応',
    petAllowed: 'allowed',
    sects: [],
    supportedMemorialTypes: ['general', 'jumokusou', 'eitai_kuyou', 'noukotsudou'],
    nearestStations: [
      { name: '鴨居駅', line: 'JR横浜線', walk: 999 },
    ],
    priceAggMin: 188000,
    priceAggMax: 2000000,
    managementFeeAggType: 'annual',
    catchphrase: '横浜最大級の総合霊園。多彩な供養スタイルに対応',
    overview: '横浜市緑区に広がる大型総合霊園。一般墓地、樹木葬、納骨堂、永代供養など、あらゆる供養スタイルに対応。無料シャトルバスを毎日運行しており、アクセスも便利です。',
    suitableFor: ['家族全員のプランをまとめたい', '選択肢を幅広く比較したい'],
    notesPoints: ['シャトルバスは1時間に2本運行', '見学・相談は予約不要'],
    tags: ['横浜', '緑区', '総合霊園', '樹木葬', 'ペット可'],
    phone: '045-000-0001',
    officeHours: '9:00〜17:00（年中無休）',
    status: 'public',
    listedInSearch: true,
    zipCode: '226-0016',
    planType: 'free',
    plans: [
      {
        category: 'jumokusou',
        name: '樹木葬 さくらプラン',
        price: 288000,
        managementFee: 0,
        availability: 'available',
        burialMethod: 'tree',
        periodType: 'perpetual',
        capacity: '2名',
        petAllowed: 'allowed',
        order: 0,
      },
      {
        category: 'eitai_kuyou',
        name: '永代供養（個別10年）',
        price: 188000,
        managementFee: 5000,
        availability: 'available',
        burialMethod: 'burial',
        periodType: 'fixed',
        periodYears: 10,
        petAllowed: 'no',
        order: 1,
      },
      {
        category: 'general',
        name: '一般墓地 和型（2㎡）',
        price: 2000000,
        priceNote: '墓石・工事費含む',
        managementFee: 18000,
        availability: 'available',
        burialMethod: 'burial',
        periodType: 'perpetual',
        petAllowed: 'no',
        order: 2,
      },
    ],
  },

  // ── 愛知県 ──────────────────────────────────────────────────
  {
    name: '名古屋大須 大光院 永代供養',
    kana: 'なごやおおす だいこういん えいたいくよう',
    type: FacilityType.templeGrave,
    religion: ReligionCategory.buddhism,
    buddhistSect: BuddhistSect.jodoShin,
    prefecture: '愛知県',
    prefectureCode: 23,
    cityName: '名古屋市中区',
    addressLine: '大須3-22-10',
    address: '愛知県名古屋市中区大須3-22-10',
    lat: 35.1601,
    lng: 136.8990,
    access: '地下鉄大須観音駅より徒歩3分',
    parkingAvailable: false,
    indoorOutdoor: 'outdoor',
    barrierFree: true,
    petAllowed: 'no',
    sects: ['jodoShin'],
    supportedMemorialTypes: ['eitai_kuyou', 'noukotsudou'],
    nearestStations: [
      { name: '大須観音駅', line: '名古屋市営地下鉄鶴舞線', walk: 3 },
    ],
    priceAggMin: 80000,
    priceAggMax: 600000,
    managementFeeAggType: 'annual',
    catchphrase: '大須商店街に隣接。アクセス抜群の浄土真宗の寺院',
    overview: '名古屋市中区大須に位置する浄土真宗の寺院。大須観音の近くに立地し、買い物ついでにお参りができる利便性の高さが魅力。宗派を問わず受け入れを行っています。',
    suitableFor: ['名古屋市内でアクセス重視', '浄土真宗のご縁がある'],
    notesPoints: ['駐車場なし（近隣パーキング利用）', '毎月28日に月例法要'],
    tags: ['名古屋', '大須', '永代供養', '浄土真宗'],
    phone: '052-000-0001',
    officeHours: '9:00〜17:00（年中無休）',
    status: 'public',
    listedInSearch: true,
    zipCode: '460-0011',
    planType: 'free',
    plans: [
      {
        category: 'eitai_kuyou',
        name: '個別永代供養（壇）',
        price: 600000,
        managementFee: 8000,
        availability: 'available',
        burialMethod: 'burial',
        periodType: 'fixed',
        periodYears: 33,
        capacity: '2名',
        petAllowed: 'no',
        order: 0,
      },
      {
        category: 'eitai_kuyou',
        name: '合祀永代供養',
        price: 80000,
        managementFee: 0,
        availability: 'available',
        burialMethod: 'ossuary',
        periodType: 'perpetual',
        petAllowed: 'no',
        order: 1,
      },
    ],
  },

  // ── 京都府 ──────────────────────────────────────────────────
  {
    name: '東山 知恩院 永代供養墓',
    kana: 'ひがしやま ちおんいん えいたいくようぼ',
    type: FacilityType.templeGrave,
    religion: ReligionCategory.buddhism,
    buddhistSect: BuddhistSect.jodo,
    prefecture: '京都府',
    prefectureCode: 26,
    cityName: '京都市東山区',
    addressLine: '林下町400',
    address: '京都府京都市東山区林下町400',
    lat: 35.0045,
    lng: 135.7828,
    access: '地下鉄東西線 東山駅より徒歩10分',
    parkingAvailable: true,
    parking: '境内駐車場（有料）',
    indoorOutdoor: 'outdoor',
    barrierFree: false,
    petAllowed: 'no',
    sects: ['jodo'],
    supportedMemorialTypes: ['eitai_kuyou', 'general'],
    nearestStations: [
      { name: '東山駅', line: '京都市営地下鉄東西線', walk: 10 },
    ],
    priceAggMin: 200000,
    priceAggMax: 2000000,
    managementFeeAggType: 'annual',
    catchphrase: '浄土宗の総本山・知恩院の境内に眠る、格別の安らぎ',
    overview: '浄土宗の総本山として知られる知恩院の境内に設けられた永代供養墓。京都の歴史的な景観の中で、伝統的な法要と手厚い供養が受けられます。',
    suitableFor: ['浄土宗のご縁がある', '格式ある寺院を希望', '京都にゆかりがある'],
    notesPoints: ['急な石段あり・高齢者は注意', '法要日は境内が混雑することあり'],
    tags: ['京都', '東山', '知恩院', '浄土宗', '永代供養', '世界遺産'],
    phone: '075-000-0001',
    officeHours: '9:00〜16:00',
    status: 'public',
    listedInSearch: true,
    zipCode: '605-0062',
    planType: 'free',
    plans: [
      {
        category: 'eitai_kuyou',
        name: '境内個別墓（石碑型）',
        price: 2000000,
        managementFee: 25000,
        availability: 'available',
        burialMethod: 'burial',
        periodType: 'fixed',
        periodYears: 50,
        capacity: '夫婦2名',
        petAllowed: 'no',
        order: 0,
      },
      {
        category: 'eitai_kuyou',
        name: '合祀墓',
        price: 200000,
        managementFee: 0,
        availability: 'available',
        burialMethod: 'ossuary',
        periodType: 'perpetual',
        petAllowed: 'no',
        order: 1,
      },
    ],
  },

  // ── 福岡県 ──────────────────────────────────────────────────
  {
    name: '博多 承天寺 永代供養',
    kana: 'はかた じょうてんじ えいたいくよう',
    type: FacilityType.templeGrave,
    religion: ReligionCategory.buddhism,
    buddhistSect: BuddhistSect.rinzai,
    prefecture: '福岡県',
    prefectureCode: 40,
    cityName: '福岡市博多区',
    addressLine: '博多区承天寺通り2-4',
    address: '福岡県福岡市博多区承天寺通り2-4',
    lat: 33.5894,
    lng: 130.4125,
    access: '地下鉄祇園駅より徒歩5分',
    parkingAvailable: true,
    parking: '近隣提携駐車場（2時間無料）',
    indoorOutdoor: 'outdoor',
    barrierFree: true,
    petAllowed: 'no',
    sects: ['rinzai'],
    supportedMemorialTypes: ['eitai_kuyou', 'jumokusou'],
    nearestStations: [
      { name: '祇園駅', line: '福岡市地下鉄空港線', walk: 5 },
    ],
    priceAggMin: 150000,
    priceAggMax: 700000,
    managementFeeAggType: 'annual',
    catchphrase: '博多の中心地に位置する禅寺の永代供養。うどん発祥の地としても有名',
    overview: '博多うどんやざるうどんの発祥地として知られる承天寺。臨済宗の名刹として、伝統的な禅の雰囲気の中で丁寧な供養を提供しています。',
    suitableFor: ['福岡市内でアクセス重視', '禅宗のご縁がある'],
    notesPoints: ['うどん供養祭は毎年1月に開催', '見学は随時可能'],
    tags: ['福岡', '博多', '禅宗', '永代供養', '樹木葬'],
    phone: '092-000-0001',
    officeHours: '9:00〜17:00（年中無休）',
    status: 'public',
    listedInSearch: true,
    zipCode: '812-0039',
    planType: 'free',
    plans: [
      {
        category: 'eitai_kuyou',
        name: '個別永代供養（33年）',
        price: 700000,
        managementFee: 8000,
        availability: 'available',
        burialMethod: 'burial',
        periodType: 'fixed',
        periodYears: 33,
        capacity: '2名',
        petAllowed: 'no',
        order: 0,
      },
      {
        category: 'jumokusou',
        name: '樹木葬 博多プラン',
        price: 250000,
        managementFee: 0,
        availability: 'available',
        burialMethod: 'tree',
        periodType: 'perpetual',
        capacity: '1名',
        petAllowed: 'no',
        order: 1,
      },
      {
        category: 'eitai_kuyou',
        name: '合祀供養',
        price: 150000,
        managementFee: 0,
        availability: 'available',
        burialMethod: 'ossuary',
        periodType: 'perpetual',
        petAllowed: 'no',
        order: 2,
      },
    ],
  },

  // ── 埼玉県 ──────────────────────────────────────────────────
  {
    name: '大宮氷川霊園',
    kana: 'おおみやひかわれいえん',
    type: FacilityType.privateGraveyard,
    religion: ReligionCategory.unknown,
    prefecture: '埼玉県',
    prefectureCode: 11,
    cityName: 'さいたま市大宮区',
    addressLine: '高鼻町3-1-5',
    address: '埼玉県さいたま市大宮区高鼻町3-1-5',
    lat: 35.9172,
    lng: 139.6310,
    access: 'JR大宮駅より徒歩15分／無料シャトルバスあり',
    parkingAvailable: true,
    parking: '無料駐車場50台',
    indoorOutdoor: 'outdoor',
    barrierFree: true,
    petAllowed: 'allowed',
    sects: [],
    supportedMemorialTypes: ['general', 'jumokusou', 'eitai_kuyou'],
    nearestStations: [
      { name: '大宮駅', line: 'JR京浜東北線', walk: 15 },
    ],
    priceAggMin: 168000,
    priceAggMax: 1500000,
    managementFeeAggType: 'annual',
    catchphrase: '氷川神社の杜に隣接。さいたま市最大級の民営霊園',
    overview: '大宮氷川神社に隣接する民営霊園。広大な敷地に多彩なプランを揃え、宗旨・宗派を問わず受け入れています。ペット同伴でのお参りも可能。大宮駅から無料シャトルバスあり。',
    suitableFor: ['埼玉・東京北部からアクセスしやすい', '宗派不問', 'ペット可'],
    notesPoints: ['年間管理費が必要です', '資料請求で見学ツアー無料参加'],
    tags: ['さいたま', '大宮', '民営霊園', '樹木葬', 'ペット可'],
    phone: '048-000-0001',
    officeHours: '9:00〜17:00（年中無休）',
    status: 'public',
    listedInSearch: true,
    zipCode: '330-0803',
    planType: 'free',
    plans: [
      {
        category: 'general',
        name: '一般墓地（和型）',
        price: 1500000,
        priceNote: '墓石・永代使用料込み',
        managementFee: 15000,
        availability: 'available',
        burialMethod: 'burial',
        periodType: 'perpetual',
        petAllowed: 'allowed',
        order: 0,
      },
      {
        category: 'jumokusou',
        name: '樹木葬（花壇型）',
        price: 298000,
        managementFee: 0,
        availability: 'available',
        burialMethod: 'tree',
        periodType: 'perpetual',
        capacity: '2名',
        petAllowed: 'allowed',
        order: 1,
      },
      {
        category: 'eitai_kuyou',
        name: '永代供養合祀',
        price: 168000,
        managementFee: 0,
        availability: 'available',
        burialMethod: 'ossuary',
        periodType: 'perpetual',
        petAllowed: 'no',
        order: 2,
      },
    ],
  },

  // ── 千葉県 ──────────────────────────────────────────────────
  {
    name: '千葉メモリアル 船橋',
    kana: 'ちばめもりある ふなばし',
    type: FacilityType.complex,
    religion: ReligionCategory.unknown,
    prefecture: '千葉県',
    prefectureCode: 12,
    cityName: '船橋市',
    addressLine: '北本町1-15-3',
    address: '千葉県船橋市北本町1-15-3',
    lat: 35.6987,
    lng: 139.9852,
    access: 'JR総武線 船橋駅より徒歩10分',
    parkingAvailable: true,
    parking: '無料駐車場30台',
    indoorOutdoor: 'outdoor',
    barrierFree: true,
    petAllowed: 'allowed',
    sects: [],
    supportedMemorialTypes: ['general', 'jumokusou', 'eitai_kuyou', 'noukotsudou'],
    nearestStations: [
      { name: '船橋駅', line: 'JR総武線', walk: 10 },
    ],
    priceAggMin: 130000,
    priceAggMax: 1200000,
    managementFeeAggType: 'annual',
    catchphrase: '船橋駅から徒歩圏内。首都圏からアクセス抜群の複合型霊園',
    overview: '千葉県船橋市に位置する複合型霊園。一般墓地から納骨堂、樹木葬まで対応。宗旨・宗派を問わず、ペット同伴でのお参りも可能です。',
    suitableFor: ['首都圏からアクセスしやすい', '多彩なプランを比較したい'],
    notesPoints: ['年間管理費が必要なプランあり', '毎月第3土曜日に合同法要'],
    tags: ['船橋', '千葉', '複合型', '樹木葬', 'ペット可'],
    phone: '047-000-0001',
    officeHours: '9:00〜17:30（年中無休）',
    status: 'public',
    listedInSearch: true,
    zipCode: '273-0005',
    planType: 'free',
    plans: [
      {
        category: 'jumokusou',
        name: '樹木葬 里山プラン',
        price: 230000,
        managementFee: 0,
        availability: 'available',
        burialMethod: 'tree',
        periodType: 'perpetual',
        capacity: '2名',
        petAllowed: 'allowed',
        order: 0,
      },
      {
        category: 'noukotsudou',
        name: '室内納骨堂 個別壇',
        price: 380000,
        managementFee: 10000,
        availability: 'available',
        burialMethod: 'indoor',
        periodType: 'perpetual',
        capacity: '2名',
        petAllowed: 'no',
        order: 1,
      },
      {
        category: 'eitai_kuyou',
        name: '合祀永代供養',
        price: 130000,
        managementFee: 0,
        availability: 'available',
        burialMethod: 'ossuary',
        periodType: 'perpetual',
        petAllowed: 'no',
        order: 2,
      },
    ],
  },

  // ── 兵庫県 ──────────────────────────────────────────────────
  {
    name: '神戸 須磨寺 樹木葬',
    kana: 'こうべ すまでら じゅもくそう',
    type: FacilityType.templeGrave,
    religion: ReligionCategory.buddhism,
    buddhistSect: BuddhistSect.shingon,
    prefecture: '兵庫県',
    prefectureCode: 28,
    cityName: '神戸市須磨区',
    addressLine: '須磨寺町4-6-8',
    address: '兵庫県神戸市須磨区須磨寺町4-6-8',
    lat: 34.6498,
    lng: 135.1253,
    access: '山陽電鉄 須磨寺駅より徒歩5分',
    parkingAvailable: true,
    parking: '境内駐車場（無料）',
    indoorOutdoor: 'outdoor',
    barrierFree: false,
    petAllowed: 'no',
    sects: ['shingon'],
    supportedMemorialTypes: ['jumokusou', 'eitai_kuyou'],
    nearestStations: [
      { name: '須磨寺駅', line: '山陽電気鉄道本線', walk: 5 },
    ],
    priceAggMin: 198000,
    priceAggMax: 750000,
    managementFeeAggType: 'none',
    catchphrase: '源平ゆかりの古刹で、海を望む自然に囲まれた樹木葬',
    overview: '源義経ゆかりの名刹・須磨寺の境内に設けられた樹木葬区画。六甲山系の緑に囲まれ、瀬戸内海を望む絶好のロケーション。真言宗の寺院ですが宗派を問わず受け入れています。',
    suitableFor: ['歴史・自然を重視', '神戸・阪神エリアにゆかりがある'],
    notesPoints: ['急な坂道あり（高齢の方はご注意）', '見学は随時可'],
    tags: ['神戸', '須磨', '真言宗', '樹木葬', '永代供養', '歴史'],
    phone: '078-000-0001',
    officeHours: '9:00〜16:30',
    status: 'public',
    listedInSearch: true,
    zipCode: '654-0055',
    planType: 'free',
    plans: [
      {
        category: 'jumokusou',
        name: '樹木葬 海望プラン',
        price: 480000,
        managementFee: 0,
        availability: 'available',
        burialMethod: 'tree',
        periodType: 'perpetual',
        capacity: '2名',
        petAllowed: 'no',
        order: 0,
      },
      {
        category: 'jumokusou',
        name: '樹木葬 里山プラン（個人）',
        price: 198000,
        managementFee: 0,
        availability: 'available',
        burialMethod: 'tree',
        periodType: 'perpetual',
        capacity: '1名',
        petAllowed: 'no',
        order: 1,
      },
      {
        category: 'eitai_kuyou',
        name: '合祀永代供養',
        price: 750000,
        managementFee: 0,
        availability: 'available',
        burialMethod: 'ossuary',
        periodType: 'perpetual',
        petAllowed: 'no',
        order: 2,
      },
    ],
  },
]

async function main() {
  console.log('🌱 Seeding temples...')

  for (const templeData of temples) {
    const { plans, ...temple } = templeData

    const templeId = randomUUID()

    const { data: created, error: templeErr } = await supabase
      .from('temples')
      .insert(Object.fromEntries(
        Object.entries({
          id: templeId,
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
          name: temple.name,
          kana: temple.kana,
          type: temple.type,
          management_body: temple.managementBody,
          religion: temple.religion,
          buddhist_sect: temple.buddhistSect,
          prefecture: temple.prefecture,
          prefecture_code: temple.prefectureCode,
          city_name: temple.cityName,
          address_line: temple.addressLine,
          address: temple.address,
          lat: temple.lat,
          lng: temple.lng,
          access: temple.access,
          parking_available: temple.parkingAvailable,
          parking: temple.parking,
          indoor_outdoor: temple.indoorOutdoor,
          barrier_free: temple.barrierFree,
          barrier_free_label: temple.barrierFreeLabel,
          pet_allowed: temple.petAllowed,
          sects: temple.sects,
          supported_memorial_types: temple.supportedMemorialTypes,
          nearest_stations: temple.nearestStations,
          price_agg_min: temple.priceAggMin,
          price_agg_max: temple.priceAggMax,
          management_fee_agg_type: temple.managementFeeAggType,
          catchphrase: temple.catchphrase,
          overview: temple.overview,
          suitable_for: temple.suitableFor,
          notes_points: temple.notesPoints,
          tags: temple.tags,
          phone: temple.phone,
          office_hours: temple.officeHours,
          status: temple.status,
          listed_in_search: temple.listedInSearch,
          zip_code: temple.zipCode,
          plan_type: temple.planType,
        }).filter(([, v]) => v !== undefined)
      ))
      .select('id, name, prefecture')
      .single()

    if (templeErr || !created) {
      console.error(`❌ Failed: ${temple.name}`, templeErr?.message)
      continue
    }

    const now = new Date().toISOString()
    const plansPayload = plans.map((p) => ({
      id: randomUUID(),
      temple_id: created.id,
      created_at: now,
      updated_at: now,
      category: p.category,
      name: p.name,
      sub_description: p.subDescription,
      price: p.price,
      price_note: p.priceNote,
      management_fee: p.managementFee ?? 0,
      availability: p.availability ?? 'available',
      burial_method: p.burialMethod,
      period_type: p.periodType ?? 'perpetual',
      period_years: p.periodYears,
      capacity: p.capacity,
      capacity_note: p.capacityNote,
      pet_allowed: p.petAllowed,
      images: p.images ?? [],
      note: p.note,
      order: p.order ?? 0,
    }))

    const { error: planErr } = await supabase.from('plans').insert(plansPayload)
    if (planErr) console.error(`  ⚠️ Plans failed for ${created.name}:`, planErr.message)

    console.log(`✅ ${created.prefecture} - ${created.name} (${created.id})`)
  }

  console.log(`\n✨ Done. ${temples.length} temples seeded.`)
}

main().catch((e) => {
  console.error('❌ Seed failed:', e)
  process.exit(1)
})
